// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoodPickup.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoodPickup.Api.Data.Migrations
{
    [DbContext(typeof(MoodPickupDbContext))]
    [Migration("20260806072221_Sprint3MenuDomain")]
    partial class Sprint3MenuDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoodPickup.Api.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("IsDeleted", "IsVisible", "DisplayOrder");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categories_DisplayOrder_NonNegative", "\"DisplayOrder\" >= 0");

                            t.HasCheckConstraint("CK_Categories_Name_Trimmed", "trim(\"Name\") = \"Name\" AND length(\"Name\") > 0");
                        });
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("TelegramChatId")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.EmployeeRole", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("EmployeeId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("EmployeeRoles", (string)null);
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.LoginChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaximumAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RequestIpHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserAgentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber", "CreatedAt");

                    b.HasIndex("RequestIpHash", "CreatedAt");

                    b.ToTable("LoginChallenges", (string)null);
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByEmployeeId");

                    b.HasIndex("IsDeleted", "CreatedAt");

                    b.HasIndex("StorageProvider", "StorageKey")
                        .IsUnique();

                    b.ToTable("MediaFiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_MediaFiles_FileSizeBytes_NonNegative", "\"FileSizeBytes\" >= 0");

                            t.HasCheckConstraint("CK_MediaFiles_Height_Positive", "\"Height\" IS NULL OR \"Height\" > 0");

                            t.HasCheckConstraint("CK_MediaFiles_Width_Positive", "\"Width\" IS NULL OR \"Width\" > 0");
                        });
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.OptionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DefaultIsRequired")
                        .HasColumnType("boolean");

                    b.Property<int?>("DefaultMaximumSelections")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultMinimumSelections")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("SelectionType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("IsDeleted", "IsActive", "DisplayOrder");

                    b.ToTable("OptionGroups", null, t =>
                        {
                            t.HasCheckConstraint("CK_OptionGroups_DefaultMaximumSelections_Positive", "\"DefaultMaximumSelections\" IS NULL OR \"DefaultMaximumSelections\" >= 1");

                            t.HasCheckConstraint("CK_OptionGroups_DefaultMinimumSelections_NonNegative", "\"DefaultMinimumSelections\" >= 0");

                            t.HasCheckConstraint("CK_OptionGroups_DefaultSelectionRange", "\"DefaultMaximumSelections\" IS NULL OR \"DefaultMinimumSelections\" <= \"DefaultMaximumSelections\"");

                            t.HasCheckConstraint("CK_OptionGroups_DisplayOrder_NonNegative", "\"DisplayOrder\" >= 0");

                            t.HasCheckConstraint("CK_OptionGroups_Name_Trimmed", "trim(\"Name\") = \"Name\" AND length(\"Name\") > 0");

                            t.HasCheckConstraint("CK_OptionGroups_RequiredMinimum", "NOT \"DefaultIsRequired\" OR \"DefaultMinimumSelections\" >= 1");

                            t.HasCheckConstraint("CK_OptionGroups_SingleMaximum", "\"SelectionType\" <> 'Single' OR \"DefaultMaximumSelections\" IS NULL OR \"DefaultMaximumSelections\" <= 1");
                        });
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.OptionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("OptionGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OptionGroupId", "NormalizedName")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.HasIndex("OptionGroupId", "IsDeleted", "IsActive", "DisplayOrder");

                    b.ToTable("OptionValues", null, t =>
                        {
                            t.HasCheckConstraint("CK_OptionValues_DisplayOrder_NonNegative", "\"DisplayOrder\" >= 0");

                            t.HasCheckConstraint("CK_OptionValues_Name_Trimmed", "trim(\"Name\") = \"Name\" AND length(\"Name\") > 0");
                        });
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DefaultCalories")
                        .HasColumnType("integer");

                    b.Property<int?>("DefaultVolumeMilliliters")
                        .HasColumnType("integer");

                    b.Property<int?>("DefaultWeightGrams")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ingredients")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("IsDeleted", "IsAvailable");

                    b.HasIndex("CategoryId", "IsDeleted", "IsVisible", "DisplayOrder");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_BasePrice_NonNegative", "\"BasePrice\" >= 0");

                            t.HasCheckConstraint("CK_Products_DefaultCalories_NonNegative", "\"DefaultCalories\" IS NULL OR \"DefaultCalories\" >= 0");

                            t.HasCheckConstraint("CK_Products_DefaultVolumeMilliliters_NonNegative", "\"DefaultVolumeMilliliters\" IS NULL OR \"DefaultVolumeMilliliters\" >= 0");

                            t.HasCheckConstraint("CK_Products_DefaultWeightGrams_NonNegative", "\"DefaultWeightGrams\" IS NULL OR \"DefaultWeightGrams\" >= 0");

                            t.HasCheckConstraint("CK_Products_DisplayOrder_NonNegative", "\"DisplayOrder\" >= 0");

                            t.HasCheckConstraint("CK_Products_Name_Trimmed", "trim(\"Name\") = \"Name\" AND length(\"Name\") > 0");
                        });
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.ProductOptionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("MaximumSelections")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumSelections")
                        .HasColumnType("integer");

                    b.Property<Guid>("OptionGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OptionGroupId");

                    b.HasIndex("ProductId", "OptionGroupId")
                        .IsUnique();

                    b.HasIndex("ProductId", "IsActive", "DisplayOrder");

                    b.ToTable("ProductOptionGroups", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductOptionGroups_DisplayOrder_NonNegative", "\"DisplayOrder\" >= 0");

                            t.HasCheckConstraint("CK_ProductOptionGroups_MaximumSelections_Positive", "\"MaximumSelections\" >= 1");

                            t.HasCheckConstraint("CK_ProductOptionGroups_MinimumSelections_NonNegative", "\"MinimumSelections\" >= 0");

                            t.HasCheckConstraint("CK_ProductOptionGroups_RequiredMinimum", "NOT \"IsRequired\" OR \"MinimumSelections\" >= 1");

                            t.HasCheckConstraint("CK_ProductOptionGroups_SelectionRange", "\"MinimumSelections\" <= \"MaximumSelections\"");
                        });
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.ProductOptionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Calories")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OptionValueId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PriceModifier")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("ProductOptionGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VolumeMilliliters")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OptionValueId");

                    b.HasIndex("ProductOptionGroupId", "OptionValueId")
                        .IsUnique();

                    b.HasIndex("ProductOptionGroupId", "IsAvailable", "DisplayOrder");

                    b.ToTable("ProductOptionValues", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductOptionValues_Calories_NonNegative", "\"Calories\" IS NULL OR \"Calories\" >= 0");

                            t.HasCheckConstraint("CK_ProductOptionValues_DisplayOrder_NonNegative", "\"DisplayOrder\" >= 0");

                            t.HasCheckConstraint("CK_ProductOptionValues_PriceModifier_NonNegative", "\"PriceModifier\" >= 0");

                            t.HasCheckConstraint("CK_ProductOptionValues_VolumeMilliliters_NonNegative", "\"VolumeMilliliters\" IS NULL OR \"VolumeMilliliters\" >= 0");
                        });
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIpHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIpHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserAgentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FamilyId");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_RefreshTokens_AccountOwner", "(\"AccountType\" = 'Customer' AND \"CustomerId\" IS NOT NULL AND \"EmployeeId\" IS NULL) OR (\"AccountType\" = 'Employee' AND \"EmployeeId\" IS NOT NULL AND \"CustomerId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.EmployeeRole", b =>
                {
                    b.HasOne("MoodPickup.Api.Entities.Employee", "Employee")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoodPickup.Api.Entities.Role", "Role")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.MediaFile", b =>
                {
                    b.HasOne("MoodPickup.Api.Entities.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedByEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByEmployee");
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.OptionValue", b =>
                {
                    b.HasOne("MoodPickup.Api.Entities.OptionGroup", "OptionGroup")
                        .WithMany("Values")
                        .HasForeignKey("OptionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OptionGroup");
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.Product", b =>
                {
                    b.HasOne("MoodPickup.Api.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoodPickup.Api.Entities.MediaFile", "Image")
                        .WithMany("Products")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.ProductOptionGroup", b =>
                {
                    b.HasOne("MoodPickup.Api.Entities.OptionGroup", "OptionGroup")
                        .WithMany("ProductAssignments")
                        .HasForeignKey("OptionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoodPickup.Api.Entities.Product", "Product")
                        .WithMany("OptionGroups")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OptionGroup");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.ProductOptionValue", b =>
                {
                    b.HasOne("MoodPickup.Api.Entities.OptionValue", "OptionValue")
                        .WithMany("ProductAssignments")
                        .HasForeignKey("OptionValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoodPickup.Api.Entities.ProductOptionGroup", "ProductOptionGroup")
                        .WithMany("Values")
                        .HasForeignKey("ProductOptionGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OptionValue");

                    b.Navigation("ProductOptionGroup");
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.RefreshToken", b =>
                {
                    b.HasOne("MoodPickup.Api.Entities.Customer", "Customer")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoodPickup.Api.Entities.Employee", "Employee")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoodPickup.Api.Entities.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("ReplacedByToken");
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.Customer", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeRoles");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.MediaFile", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.OptionGroup", b =>
                {
                    b.Navigation("ProductAssignments");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.OptionValue", b =>
                {
                    b.Navigation("ProductAssignments");
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.Product", b =>
                {
                    b.Navigation("OptionGroups");
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.ProductOptionGroup", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("MoodPickup.Api.Entities.Role", b =>
                {
                    b.Navigation("EmployeeRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
